express/urls.py
from django.conf.urls import url
from express import views

app_name = "express"
urlpatterns = [
    url(r'reserve/', views.Reserve.as_view(), name='reserve'),

]

first/urls.py
from django.conf.urls import url
from first import views

app_name = "first"
urlpatterns = [
    url(r'questionnaire', views.Questionnaire.as_view(), name='questionnaire'),

    url(r'search/', views.search.as_view(), name='search'),
    url(r'codeExchange/', views.codeExchange, name='codeExchange'),
    url(r'ClickMap/', views.onClickMap.as_view(), name='clickmap'),
    url(r'getlock/', views.getLock.as_view(), name='getlock'),
    url(r'^lock/', views.lock, name='lock'),
    url(r'^unlock/', views.unlock, name="unlock"),
]

reward/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
import xadmin

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'first/', include('first.urls')),
    url(r'express/', include('express.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

express/models.py
from django.db import models
from django.utils import timezone

class Department(models.Model):
    name = models.CharField(u'院系名', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '院系'
        verbose_name_plural = '院系'


class Grade(models.Model):
    name = models.CharField(u'班级名', max_length=100)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, verbose_name="所属院系", default=0, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '班级'
        verbose_name_plural = '班级'


class Dormitory(models.Model):
    name = models.CharField("宿舍号", max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '宿舍'
        verbose_name_plural = '宿舍'


class Student(models.Model):
    ctimeChoice = (
        ('1', '上午'),
        ('2', '下午')
    )
    grade = models.ForeignKey(Grade, on_delete=models.SET_NULL, verbose_name='班级', default=0, null=True)
    name = models.CharField(u'姓名', max_length=30, default=' ')
    dormitory = models.ForeignKey(Dormitory, verbose_name='宿舍号', on_delete=models.SET_NULL, default=0, null=True)
    address = models.CharField(u'地址', max_length=20)
    phone = models.CharField(u'联系方式', max_length=10)
    date = models.DateField(u'预定日期', default=timezone.now())
    ctime = models.CharField(u'时间', max_length=3, choices=ctimeChoice, default='1')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '毕业生'
        verbose_name_plural = '毕业生'

express/views.py
from django.shortcuts import render
from django.views.generic import View
from express.models import *
from django.http import HttpResponse
import json
import datetime

class Reserve(View):
    def get(self, request):
        dors = Dormitory.objects.all()
        return render(request, 'express/reserve.html', {"dors": dors})

    def post(self, request):
        dormitory = request.POST.get("dormitory", "")
        name = request.POST.get("name", "")
        ctime = request.POST.get("ctime", "")
        phone = request.POST.get("phone", "")
        date = request.POST.get("date", "")
        if dormitory and name and ctime and phone:
            date = list(map(int, date.split('-')))
            Student.objects.create(dormitory_id=int(dormitory), name=name, ctime=ctime, phone=phone, date=datetime.date(*date))
            return HttpResponse(json.dumps({"status": 1}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({"status": 2}), content_type="application/json")

templates/express/reserve.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>寄件预定</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            background: #f0f1f2;
        }
    </style>
</head>
<body>

<div class="modal fade" id="success" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">预定成功</h4>
            </div>
            <div class="modal-body" id="begin">
                <p class="text-center">可扫码添加客服</p>
                <img src="{% static 'images/group.jpg' %}" class="img-responsive center-block">
{#                <p class="text-center">现在预定赠送一次抽奖机会，快去抽奖吧</p>#}
            </div>
            <div class="modal-footer">
                <button type="button" id="finish" class="btn btn-primary btn-lg btn-block ladda-button"
                        data-dismiss="modal" data-style="zoom-out" data-size="l"><span class='ladda-label'>知道了</span>
                </button>
            </div>
        </div>
    </div>
</div>

<h1 class="text-center">寄件预定</h1>
<div id="" class="container">
    {% csrf_token %}
    <form class="form-horizontal">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">宿舍号</label>
            <div class="col-sm-10">
                <select class="form-control" id="dormitory">
                    {% for dor in dors %}
                        <option value="{{ dor.id }}">{{ dor.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">姓名</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="name" placeholder="姓名">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">联系电话</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="phone" placeholder="联系电话">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">寄件日期</label>
            <div class="col-sm-10">
                <input type="date" class="form-control" id="date" required="required">
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">具体时间</label>
            <div class="col-sm-10">
                <select class="form-control" id="ctime">
                    <option value="1">上午</option>
                    <option value="2">下午</option>
                </select>
            </div>
        </div>
    </form>
    <div class="form-group">
        <button type="submit" id="reserve" class="btn btn-primary col-xs-offset-2 col-xs-8">预定</button>
    </div>
</div>


<script src="https://libs.cdnjs.net/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script type="text/javascript">
    $("#reserve").click(function () {
        if ( $("#dormitory").val()=="" || $("#name").val()=="" || $("#ctime").val()=="" || $("#phone").val()=="" || $("#date").val()=="" ) {
            alert("请补全信息");
            return false;
        }
        $.ajax("{% url 'express:reserve' %}", {
            type: "POST",
            dataType: "json",
            data: {
                dormitory: $("#dormitory").val(),
                name: $("#name").val(),
                ctime: $("#ctime").val(),
                phone: $("#phone").val(),
                date: $("#date").val(),
                csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
            },
            success: function (res) {
                if (res.status == 1) {
                    $("#success").modal('show');
                } else {
                    alert("请补全信息");
                }
            }
        });
    });

    $("#finish").click(function () {
        {#location.href = "{% url 'first:clickmap' %}?imgid=6";#}
    });
</script>
</body>
</html>