first/urls.py
from django.conf.urls import url
from first import views

app_name = "first"
urlpatterns = [
    url(r'questionnaire', views.Questionnaire.as_view(), name='questionnaire'),

    url(r'search/', views.search.as_view(), name='search'),
    url(r'codeExchange/', views.codeExchange, name='codeExchange'),
    url(r'ClickMap/', views.onClickMap.as_view(), name='clickmap'),
    url(r'getlock/', views.getLock.as_view(), name='getlock'),
    url(r'^lock/', views.lock, name='lock'),
    url(r'^unlock/', views.unlock, name="unlock"),
]

reward/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
import xadmin

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'first/', include('first.urls')),
    url(r'express/', include('express.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/DrawAward.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>抽奖</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
     <link rel="shortcut icon" href="#" />
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<style>
		body {
			background: #f0f1f2;
		}
		h1 {
			text-align: center;
			margin: 20px 0;
            display: none;
		}
		#canvas {
			margin: 0;
			padding: 0;
			border: 1px solid #ccc;
			background-image: url("{% static 'images/draw1.jpg' %}");
			background-size: 100% 100%;
            width: 100%;
		}
		#finish {
			position: fixed;
			background: rgba(0,0,0,0);
			width: 32%;
			height: 8%;
			top: 83%;
			left: 34%;
		}

		#award {
			font-weight: bold;
			margin-left: 5px;
		}
		#code {
			font-weight: bold;
			margin-left: 5px;
		}
	</style>
</head>
<body>
    <div class="modal fade" id="rule" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">说明</h4>
                </div>
                <div class="modal-body">
                    <p class="text-center">画符召唤奖品</p>
                    <p class="text-center">PS：心诚则灵</p>
                    <img src="{% static 'images/fu.png' %}" class="img-responsive center-block">
                </div>
                <div class="modal-footer">
                    <button type="button" id="to_info" class="btn btn-primary btn-lg btn-block ladda-button" data-dismiss="modal" data-style="zoom-out" data-size="l"><span class='ladda-label'>开始抽奖</span> </button>
                </div>
            </div>
        </div>
    </div>

	<div class="modal fade" id="result" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">结果</h4>
                </div>
                <div class="modal-body">
                    <p class="text-center">恭喜你，抽中<span id="award">旅游奖</span></p>
                    <p class="text-center">兑奖码<span id="code">WTlkdaD</span></p>
                    <p class="text-center">关注公众号回复兑奖码即可获得奖品，快去关注吧</p>
                    <img src="{% static 'images/group.jpg' %}" class="img-responsive center-block">
                </div>
              <!--   <div class="modal-footer">
                    <button type="button" id="to_info" class="btn btn-primary btn-lg btn-block ladda-button" data-dismiss="modal" data-style="zoom-out" data-size="l"><span class='ladda-label'>完善信息</span> </button>
                </div> -->
            </div>
        </div>
    </div>

	<h1 id="title">画符召唤奖品</h1>
	<div id="finish"></div>
	<div><canvas id="canvas"></canvas></div>

<script src="https://libs.cdnjs.net/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript">
    $("#rule").modal('show');
	$("#finish").click(function() {
		// $.ajax({
		// 	url: '/identify/',
		// 	type: "post",
		// 	dataType: 'json',
		// 	data: {
		// 		'image': image.src,
		// 		'csrfmiddlewaretoken': $("input[type='hidden']").val(),
		// 	},
		// 	success: function(res) {
		// 		$("#number").text(res);
		// 		identified = true;
		// 	}
		// })
		$("#result").modal('show');
	});

	context = document.getElementById('canvas').getContext("2d");
	var CanvasWidth =  window.screen.width;
	var CanvasHeight = window.screen.availHeight - 10;
	var identified = false;   // 识别标志
	document.getElementById("canvas").width = CanvasWidth;
	document.getElementById("canvas").height = CanvasHeight;


	var clickX = new Array();
	var clickY = new Array();
	var clickDrag = new Array();
	var paint;

	function addClick(x, y, dragging)
	{
		clickX.push(x);
		clickY.push(y);
		clickDrag.push(dragging);
	}

	function redraw(){
		canvas.width = canvas.width; // Clears the canvas

		context.strokeStyle = "red";
		context.lineJoin = "round";
		context.lineWidth = 5;

		for(var i=0; i < clickX.length; i++) {
			context.beginPath();
			if(clickDrag[i] && i){//当是拖动而且i!=0时，从上一个点开始画线。
				context.moveTo(clickX[i-1], clickY[i-1]);
			}else{
				context.moveTo(clickX[i]-1, clickY[i]);
			}
			context.lineTo(clickX[i], clickY[i]);
			context.closePath();
			context.stroke();
		}
	}


	$('#canvas').mousedown(function(e){
		if (identified) {
			context.clearRect(0, 0, CanvasWidth, CanvasHeight);
			identified = false;
			clickX = new Array();
			clickY = new Array();
			clickDrag = new Array();
		}
		var mouseX = e.pageX - this.offsetLeft;
		var mouseY = e.pageY - this.offsetTop;

		paint = true;
		addClick(mouseX, mouseY);
		redraw();
		console.log('pc down')
	});
	$('#canvas').mousemove(function(e){
		if(paint) {//是不是按下了鼠标
			addClick(e.pageX - this.offsetLeft, e.pageY - this.offsetTop, true);
			redraw();
		}
		console.log('pc move')
	});
	$('#canvas').mouseup(function(e){
		paint = false;
	});
	$('#canvas').mouseleave(function(e){
		paint = false;
	});


	$("#Identify").click(function() {
		var image = new Image();
		image.src = canvas.toDataURL("image/png");

		$.ajax({
			url: '/identify/',
			type: "post",
			dataType: 'json',
			data: {
				'image': image.src,
				'csrfmiddlewaretoken': $("input[type='hidden']").val(),
			},
			success: function(res) {
				$("#number").text(res);
				identified = true;
			}
		})
	});

	$("#clear").click(function() {
		context.clearRect(0, 0, CanvasWidth, CanvasHeight);
		identified = false;
		clickX = new Array();
		clickY = new Array();
		clickDrag = new Array();
	});

	oCanvas = document.getElementById("canvas");
	//手指触摸屏幕可记录此时的位置作为起点
	oCanvas.addEventListener("touchstart",function(e){
		event.preventDefault();
		if (identified) {
			context.clearRect(0, 0, CanvasWidth, CanvasHeight);
			identified = false;
			clickX = new Array();
			clickY = new Array();
			clickDrag = new Array();
		}
		var mouseX = event.changedTouches[0].clientX - e.target.offsetLeft;
		var mouseY = event.changedTouches[0].clientY - e.target.offsetTop;

		paint = true;
		addClick(mouseX, mouseY);
		redraw();
		console.log('ac down')
	});

	//手指屏滑动画线
	oCanvas.addEventListener("touchmove",function(e){
		if(paint) {//是不是按下了鼠标
			var mouseX = event.changedTouches[0].clientX - e.target.offsetLeft;
			var mouseY = event.changedTouches[0].clientY - e.target.offsetTop;
			addClick(mouseX, mouseY, true);
			redraw();
		}
		console.log('ac move')
	});
	oCanvas.addEventListener("touchend", function() {
		paint = false;
	})
</script>
</body>
</html>

templates/clickmap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>抽奖</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            background: #f0f1f2;
        }

        #image {
            max-width: 100%;
            height: auto;
            display: block;
        }

        #award {
            font-weight: bold;
            margin-left: 5px;
        }

        #code {
            font-weight: bold;
            margin-left: 5px;
        }
    </style>
</head>
<body>
<div class="modal fade" id="rule" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">找奖品</h4>
            </div>
            <div class="modal-body" id="begin">
                <p class="text-center">动动你发财的小手</p>
                <p class="text-center">点击图片任何位置即可参与一次抽奖</p>
                <p class="text-center">您共有两次机会，祝君好运 ^_^</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="finish" class="btn btn-primary btn-lg btn-block ladda-button"
                        data-dismiss="modal" data-style="zoom-out" data-size="l"><span class='ladda-label'>我准备好了</span>
                </button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="result" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">结果</h4>
            </div>
            <div class="modal-body">
                <p class="text-center">恭喜你，抽中<span id="award"></span></p>
                <p class="text-center">兑奖码<span id="code"></span></p>
                <p class="text-center">请截屏保存后添加客服兑奖</p>
                <img src="{% static 'images/group.jpg' %}" class="img-responsive center-block">
            </div>
            <!--   <div class="modal-footer">
                  <button type="button" id="to_info" class="btn btn-primary btn-lg btn-block ladda-button" data-dismiss="modal" data-style="zoom-out" data-size="l"><span class='ladda-label'>完善信息</span> </button>
              </div> -->
        </div>
    </div>
</div>

<div class="modal fade" id="error" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">结果</h4>
            </div>
            <div class="modal-body">
                <p class="text-center" id="error-text">没有找到奖品，还有<span id="count"></span>次机会</p>
                <p class="text-center" id="note"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-lg btn-block ladda-button" data-dismiss="modal"
                        data-style="zoom-out" data-size="l"><span class='ladda-label'>确定</span></button>
            </div>
        </div>
    </div>
</div>

{#	<h1 class="text-center">找奖品</h1>#}
{#    <p class="text-center">奖品可能藏在任何角落，点击即可抽奖</p>#}
{#    <p class="text-center">不过您只有3次机会，祝您好运</p>#}

<img id="image" class="img-responsive" src={{ img.img.url }} alt="美女" usemap="#MM">
{% csrf_token %}
<map id="MM" name="MM">
    {% for map in maps %}
        <area class="click" id="{{ map.id }}" shape="rect" coords="{{ map.area }}" href="#rect" title="矩形" alt="矩形">
    {% endfor %}
</map>

<script src="https://libs.cdnjs.net/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script type="text/javascript">

    $("#rule").modal('show');

    {% ifequal lock 1 %}
        $("#begin").html('<p class="text-center">您已参与过抽奖，再次抽奖请添加客服获取抽奖资格</p>');
        $("#finish").text("我知道了");
        $("map").remove();
        $("#image").click(function () {
            if (localStorage.finish == "1") {
                $("#rule").modal('show');
                return false;
            }
        });
    {% else %}
        var count = 2;
        var award = 0;
        $(".click").click(function (e) {
            if (award == 1) {
                $("#result").modal('show');
                return false;
            }
            if (count > 0) {
                id = e.target.id;
                $.ajax('#', {
                    type: "POST",
                    dataType: 'json',
                    data: {
                        'areaid': id,
                        'csrfmiddlewaretoken': $("input[type='hidden']").val(),
                    },
                    success: function (res) {
                        if (res.status == 1) {
                            $("#award").text(res.award);
                            $("#code").text(res.code);
                            $("#result").modal('show');
                            award = 1;
                        }
                    }
                });
            } else {
                $("#error-text").text("两次都没中，你也是没谁了");
                $("#error").modal('show')
            }
        });
        $("#image").click(function () {
            if (award == 1) {
                $("#result").modal('show');
            } else {
                count = count - 1;
                if (count > 0) {
                    $("#count").text(count);
                    if (count == 1)
                        $("#note").text("提示：{{ img.note }}");
                } else {
                    $("#note").text("");
                    $("#error-text").text("两次都没中，你也是没谁了");
                }
                $("#error").modal('show')
            }
        });

    {% endifequal %}

    $("#finish").click(function () {
        $.ajax("{% url 'first:lock' %}", {
            type: "POST",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[type='hidden']").val(),
            },
            success: function (res) {
                if (res.status == 1)
                    $("#rule").modal('hide');
            }
        });
        return false;
    });

    function adjustPosition(position) {
        // 获取宽高
        var pageWidth = $("#image").width();
        var pageHeight = $("#image").height();
        // 图片原始尺寸
        var imageWidth = document.getElementById("image").naturalWidth;
        var imageHeigth = document.getElementById("image").naturalHeight;

        var each = position.split(",");

        for (var i = 0; i < each.length; i++) {
            if (i % 2 == 0) {
                // 新的y轴坐标
                each[i] = Math.round(parseInt(each[i]) * pageHeight / imageHeigth).toString();
            } else {
                // 新的x轴坐标
                each[i] = Math.round(parseInt(each[i]) * pageWidth / imageWidth).toString();
            }
        }
        var newPosition = "";
        for (var j = 0; j < each.length; j++) {
            newPosition += each[j];
            if (j < each.length - 1) {
                newPosition += ",";
            }
        }
        return newPosition;
    }

    function adjust() {
        var map = document.getElementById("MM");
        var area = map.getElementsByTagName('area');

        for (var i = 0; i < area.length; i++) {
            var oldCoords = area[i].getAttribute("coords");
            var newcoords = adjustPosition(oldCoords);
            area[i].setAttribute("coords", newcoords);
        }
    }

    adjust();
</script>
</body>
</html>

templates/getlock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>解锁链接</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            background: #f0f1f2;
        }

        textarea {
            width: 80%;
            margin: 10px 10%;
        }
    </style>
</head>
<body>
<h1 class="text-center">解锁链接</h1>
<div id="search" class="row">
    {% csrf_token %}
    <button class="btn btn-primary col-xs-8 col-xs-offset-2" id="getcode">获取解锁链接</button>

</div>


<script src="https://libs.cdnjs.net/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    function copy(url) {
        var Url2 = url;
        var oInput = document.createElement('textarea');
        oInput.value = Url2;
        document.body.appendChild(oInput);
        oInput.select(); // 选择对象
        document.execCommand("Copy"); // 执行浏览器复制命令
        oInput.className = 'oInput';
        {#oInput.style.display = 'none';#}
        alert('获取成功,已复制至粘贴板');
    }

    $("#getcode").click(function () {
        $.ajax("#", {
            type: "POST",
            dataType: "json",
            data: {
                'csrfmiddlewaretoken': $("input[type='hidden']").val(),
            },
            success: function (res) {
                if (res.status == 1) {
                    copy(res.url);
                }
            }
        })
    });
</script>
</body>
</html>

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>兑奖查询</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            background: #f0f1f2;
        }

        #search {
            margin-top: 10px;
        }

        #search input {
            height: 34px;
        }

        #result {
            margin-top: 30px;
        }
        #result span {
            margin-left: 10px;
            font-weight: bold;
        }
    </style>
</head>
<body>
<h1 class="text-center">兑奖码查询</h1>
<div id="search" class="row">
    {% csrf_token %}
    <input type="text" id="code" placeholder="请输入兑奖码" class="col-xs-offset-1 col-xs-8 form-control-inline">
    <button class="btn btn-primary col-xs-2">查询</button>
</div>
<div id="result">
    <h3 class="col-xs-offset-1">奖励： <span id="name"></span></h3>
    <h3 class="col-xs-offset-1">使用情况：<span id="use"></span></h3>
    <button class="btn btn-primary col-xs-offset-2 col-xs-8" id="exchange">兑换</button>
</div>


<script src="https://libs.cdnjs.net/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script type="text/javascript">
    var codeId = ""
    $("#exchange").hide();
    $("#search").click(function () {
        if ($("#code").val()=="")
            return false;
        $("#name").text("");
        $("#use").text("");
        $.ajax('#', {
            type: "POST",
            dataType: "json",
            data: {
                code: $("#code").val(),
                'csrfmiddlewaretoken': $("input[type='hidden']").val(),
            },
            success: function (res) {
                if (res.status==0) {
                    $("#name").text("无")
                } else {
                    $("#name").text(res.name);
                    $("#use").text(res.use);
                    codeId=res.codeid;
                    if (res.status==2)
                        $("#exchange").hide();
                    else if (res.status ==1)
                        $("#exchange").show();
                }
            }
        })
    });

    $("#exchange").click(function () {
        $.ajax("{% url 'first:codeExchange' %}", {
            type: "POST",
            dataType: "json",
            data: {
                "codeId": codeId,
                'csrfmiddlewaretoken': $("input[type='hidden']").val(),
            },
            success: function (res) {
                if (res.status == 1) {
                    alert("兑换成功");
                    $("#use").text("已使用")
                    $("#exchange").hide();
                }
            }
        });
    });
</script>
</body>
</html>

templates/unlock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>解锁</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
    {% ifequal status 1 %}
        <p>解锁成功，你可以继续抽奖</p>
    {% else %}
        <p>解锁失败，请联系客服获得有效的解锁链接</p>
    {% endifequal %}

    <p></p>
</body>
</html>